// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistracijosPozymiai.Data;

namespace RegistracijosPozymiai.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211229195505_remodeling-FilledRegistration-table-correcting-design-mistakes")]
    partial class remodelingFilledRegistrationtablecorrectingdesignmistakes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegistracijosPozymiai.Models.FormedRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("FormedRegistrations");
                });

            modelBuilder.Entity("RegistracijosPozymiai.Models.RegAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegAttributes");
                });

            modelBuilder.Entity("RegistracijosPozymiai.Models.RegValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FormedRegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegistrationAttributeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormedRegistrationId");

                    b.HasIndex("RegistrationAttributeId");

                    b.ToTable("RegValues");
                });

            modelBuilder.Entity("RegistracijosPozymiai.Models.RegValue", b =>
                {
                    b.HasOne("RegistracijosPozymiai.Models.FormedRegistration", null)
                        .WithMany("SelectedValues")
                        .HasForeignKey("FormedRegistrationId");

                    b.HasOne("RegistracijosPozymiai.Models.RegAttribute", "RegistrationAttribute")
                        .WithMany("RegistrationValues")
                        .HasForeignKey("RegistrationAttributeId");

                    b.Navigation("RegistrationAttribute");
                });

            modelBuilder.Entity("RegistracijosPozymiai.Models.FormedRegistration", b =>
                {
                    b.Navigation("SelectedValues");
                });

            modelBuilder.Entity("RegistracijosPozymiai.Models.RegAttribute", b =>
                {
                    b.Navigation("RegistrationValues");
                });
#pragma warning restore 612, 618
        }
    }
}
